# Global settings
shell = "zsh -c '{}'"             # This tells Tinty how to run hooks
default-scheme = "base16-tarot"      # Default theme when none is specified

# ghostty
[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"    
name = "tinted-ghostty"
hook = "command cp -f %f ~/.config/ghostty/themes/tinted-theming"
themes-dir = "themes/ghostty"              

# tmux
[[items]]
path = "https://github.com/tinted-theming/tinted-tmux"
name = "tinted-tmux"
hooks = ["tmux source-file ~/.config/tmux/tmux.conf"]
themes-dir = "colors"
