# Global settings
shell = "zsh -c '{}'"             # This tells Tinty how to run hooks
default-scheme = "base16-tarot"      # Default theme when none is specified

# ghostty
[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"    
name = "tinted-ghostty"
hook = "cp -f %f ~/.config/ghostty/themes/tinted-theming && osascript ~/.config/ghostty/reload.scpt"
themes-dir = "themes/ghostty"              

# tmux
[[items]]
path = "https://github.com/tinted-theming/tinted-tmux"
name = "tinted-tmux"
hook = "tmux source-file ~/.config/tmux/tmux.conf"
themes-dir = "colors"

# pi
[[items]]
path = "https://github.com/body-clock/tinted-pi"
name = "tinted-pi"
hook = "mkdir -p ~/.pi/agent/themes && cp -f %f ~/.pi/agent/themes/tinted.json"
themes-dir = "themes"
supported-systems = ["base16", "base24"]

# omp
[[items]]
path = "~/code/tinted-omp"
name = "tinted-omp"
hook = "mkdir -p ~/.omp/agent/themes && cp -f \"$TINTY_THEME_FILE_PATH\" ~/.omp/agent/themes/tinted.json"
themes-dir = "themes"
supported-systems = ["base16", "base24"]
