#!/usr/bin/env bash
# tinty-fzf-theme.sh  —  Generate a clean fzf theme from the current tinty scheme
#
# tinty passes the generated file path as %f. We extract the --color flags
# from it and write a clean ~/.config/fzf/tinted.sh that sets FZF_DEFAULT_OPTS
# without appending (avoids unbounded growth when schemes change).
#
# Hook into tinty config.toml:
#   [[items]]
#   path = "https://github.com/tinted-theming/tinted-fzf"
#   name = "tinted-fzf"
#   hook = "bash ~/.config/tinted-theming/tinty/scripts/tinty-fzf-theme.sh %f"
#   themes-dir = "sh"

set -euo pipefail

GENERATED_FILE="${1:?Usage: tinty-fzf-theme.sh <path-to-generated-file>}"
FZF_THEME_DIR="${HOME}/.config/fzf"
FZF_THEME_FILE="${FZF_THEME_DIR}/tinted.sh"

if [ ! -f "$GENERATED_FILE" ]; then
  echo "[tinty-fzf] ERROR: generated file not found: $GENERATED_FILE" >&2
  exit 1
fi

# Extract the scheme name from the comment header
SCHEME_NAME=$(sed -n '1s/^# Scheme name: //p' "$GENERATED_FILE" | tr -d '[:space:]')
SCHEME_SYSTEM=$(sed -n '2s/^# Scheme system: //p' "$GENERATED_FILE" | tr -d '[:space:]')

# Extract the --color= flags from the FZF_DEFAULT_OPTS export.
# The generated file has one --color flag per line, spread across
# multiple continuation lines like:
#   " --color=bg+:#2a153c,bg:#0e091d,spinner:#8c9785,hl:#6e6080"\
# We extract the value portion after --color= from each line and join with commas.
COLOR_PARTS=$(sed -n 's/.*--color=\([^"]*\).*/\1/p' "$GENERATED_FILE" | paste -sd ',' -)

# Build clean export — replace, don't append, so scheme changes don't bloat FZF_DEFAULT_OPTS
mkdir -p "$FZF_THEME_DIR"

cat > "$FZF_THEME_FILE" << EOF
# tinted-fzf theme — generated by tinty
# Scheme: ${SCHEME_NAME} (${SCHEME_SYSTEM})

export FZF_DEFAULT_OPTS="--color=${COLOR_PARTS}"
EOF

echo "[tinty-fzf] wrote theme → $FZF_THEME_FILE (${SCHEME_NAME})" >&2
